name: Build Executable for RHEL7.9

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    container: centos:7   # simulate RHEL7.9 environment
    steps:
      - uses: actions/checkout@v2

      - name: Install Python & Build Tools
        run: |
          yum -y install epel-release
          yum -y install python36 python36-devel gcc make which
          python3.6 -m ensurepip
          python3.6 -m pip install --upgrade pip pyinstaller

      - name: Install Dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then
            python3.6 -m pip install -r requirements.txt
          fi

      - name: Build Executable
        run: python3.6 -m PyInstaller --onefile --noconsole main.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: rhel7-executable
          path: dist/app
