name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller
    - name: Build executable
      run: pyinstaller --onefile --name device_monitor_linux main.py
    - name: Create Kiosk package
      run: |
        mkdir -p kiosk_linux
        cp dist/device_monitor_linux kiosk_linux/device_monitor
        cp scripts/kiosk.sh kiosk_linux/
        chmod +x kiosk_linux/kiosk.sh
        tar -czvf device_monitor_linux_kiosk.tar.gz -C kiosk_linux .
    - name: Upload Linux executable
      uses: actions/upload-artifact@v3
      with:
        name: device_monitor_linux
        path: dist/device_monitor_linux
    - name: Upload Linux Kiosk package
      uses: actions/upload-artifact@v3
      with:
        name: device_monitor_linux_kiosk
        path: device_monitor_linux_kiosk.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller
    - name: Build executable
      run: pyinstaller --onefile --name device_monitor_windows main.py
    - name: Create Kiosk package
      run: |
        mkdir kiosk_windows
        copy dist\device_monitor_windows.exe kiosk_windows\device_monitor.exe
        copy scripts\kiosk.bat kiosk_windows\
        powershell -Command "Compress-Archive -Path kiosk_windows -DestinationPath device_monitor_windows_kiosk.zip"
    - name: Upload Windows executable
      uses: actions/upload-artifact@v3
      with:
        name: device_monitor_windows
        path: dist/device_monitor_windows.exe
    - name: Upload Windows Kiosk package
      uses: actions/upload-artifact@v3
      with:
        name: device_monitor_windows_kiosk
        path: device_monitor_windows_kiosk.zip
