name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: /opt/python/cp38-cp38/bin/pip install pyinstaller
    - name: Build Linux executable (no kiosk)
      run: /opt/python/cp38-cp38/bin/pyinstaller --onefile --noconsole --name device_monitor_linux main.py
    - name: Build Linux executable (with kiosk)
      run: /opt/python/cp38-cp38/bin/pyinstaller --onefile --noconsole --add-data "scripts/kiosk.sh:." --name device_monitor_linux_kiosk main.py
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-executables
        path: |
          dist/device_monitor_linux
          dist/device_monitor_linux_kiosk

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build Windows executable (no kiosk)
      run: pyinstaller --onefile --noconsole --name device_monitor_windows main.py
    - name: Build Windows executable (with kiosk)
      run: pyinstaller --onefile --noconsole --add-data "scripts/kiosk.bat;." --name device_monitor_windows_kiosk main.py
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-executables
        path: |
          dist/device_monitor_windows.exe
          dist/device_monitor_windows_kiosk.exe
