name: Build RPM Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: centos:7
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          yum install -y rpm-build make python3
          yum install -y python3-tkinter  # Dependency for the application

      - name: Create RPM build directory structure
        run: mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

      - name: Copy spec file
        run: cp .github/rpm/device-monitor.spec ~/rpmbuild/SPECS/

      - name: Create source tarball
        run: |
          # Using git archive to create a clean tarball
          git archive --format=tar.gz --prefix=device-monitor-1.0/ -o ~/rpmbuild/SOURCES/device-monitor-1.0.tar.gz HEAD

      - name: Build RPM
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/device-monitor.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: device-monitor-rpm
          path: ~/rpmbuild/RPMS/x86_64/device-monitor-*.rpm
